In [3]:
# --------------------
# Import Libraries
# --------------------
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme()

In [4]:
data = pd.read_csv('../data/raw/Amazon_Reviews.csv', engine='python')

In [5]:
# --------------------
# Dataset Information
# --------------------
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 21214 entries, 0 to 21213
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reviewer Name       21214 non-null  str
 1   Profile Link        21163 non-null  str
 2   Country             21054 non-null  str
 3   Review Count        21055 non-null  str
 4   Review Date         21055 non-null  str
 5   Rating              21055 non-null  str
 6   Review Title        21055 non-null  str
 7   Review Text         21055 non-null  str
 8   Date of Experience  20947 non-null  str
dtypes: str(9)
memory usage: 13.7 MB

In [6]:
# --------------
# Dataset Head
# --------------
data.head()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
0,Eugene ath,/users/66e8185ff1598352d6b3701a,US,1 review,2024-09-16T13:44:26.000Z,Rated 1 out of 5 stars,A Store That Doesn't Want to Sell Anything,"I registered on the website, tried to order a ...","September 16, 2024"
1,Daniel ohalloran,/users/5d75e460200c1f6a6373648c,GB,9 reviews,2024-09-16T18:26:46.000Z,Rated 1 out of 5 stars,Had multiple orders one turned up and…,Had multiple orders one turned up and driver h...,"September 16, 2024"
2,p fisher,/users/546cfcf1000064000197b88f,GB,90 reviews,2024-09-16T21:47:39.000Z,Rated 1 out of 5 stars,I informed these reprobates,I informed these reprobates that I WOULD NOT B...,"September 16, 2024"
3,Greg Dunn,/users/62c35cdbacc0ea0012ccaffa,AU,5 reviews,2024-09-17T07:15:49.000Z,Rated 1 out of 5 stars,Advertise one price then increase it on website,I have bought from Amazon before and no proble...,"September 17, 2024"
4,Sheila Hannah,/users/5ddbe429478d88251550610e,GB,8 reviews,2024-09-16T18:37:17.000Z,Rated 1 out of 5 stars,If I could give a lower rate I would,If I could give a lower rate I would! I cancel...,"September 16, 2024"

In [7]:
# --------------
# Dataset Tail
# --------------
data.tail()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
21209,Anders T,/users/47bd4ffe0000640001001044,DK,1 review,2009-03-22T13:14:12.000Z,Rated 5 out of 5 stars,Fast!!,"I have had perfect order fulfillment, and fast...","March 22, 2009"
21210,David E,/users/495bbbc0000064000100a972,US,2 reviews,2008-12-31T18:57:31.000Z,Rated 5 out of 5 stars,Consistently Excellent,"I have had perfect order fulfillment, and fast...","December 31, 2008"
21211,Joseph Harding,/users/48cfacbf0000640001005d04,GB,3 reviews,2008-09-16T13:05:05.000Z,Rated 3 out of 5 stars,Good prices but delivery can take time :(,I always find myself going back to amazon beco...,"September 16, 2008"
21212,Mads Dørup,/users/474aaec70000640001000a44,DK,82 reviews,2008-04-28T11:09:05.000Z,Rated 5 out of 5 stars,World-class online shopping,I have placed an abundance of orders with Amaz...,"April 28, 2008"
21213,Kim Fuglsang Kramer,/users/46d1ed150000640001000051,DK,2 reviews,2007-08-27T17:25:01.000Z,Rated 4 out of 5 stars,No title,"those goods i've ordered by Amazon.com, have b...","August 27, 2007"

In [8]:
# ---------------
# Dataset Sample
# ---------------
data.sample(5)

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
16331,YUSIF HAHN,/users/5d1d212159efee5e79315a88,US,1 review,2019-07-03T21:42:05.000Z,Rated 1 out of 5 stars,Amazon Doesn't care anymore.,In the last month.. They have had multiple err...,"July 03, 2019"
14420,Bob,/users/5938f9fb0000ff000aa13981,NZ,17 reviews,2020-02-03T06:22:32.000Z,Rated 1 out of 5 stars,When you check the final price there is…,When you check the final price there is no las...,"February 03, 2020"
153,Chris G,/users/66df7e01f9a29b073f146833,US,1 review,2024-09-10T01:00:28.000Z,Rated 1 out of 5 stars,Amazon Supports Cigarette Addiction and Ruins ...,"Our company, Herbal Spirits, designed and sold...","September 09, 2024"
13175,Nader Dalloul,/users/5f1f5ce42e16aa94579b4f49,US,1 review,2020-07-27T23:04:49.000Z,Rated 1 out of 5 stars,If you gig-in and waiting on amazon for your g...,Last month I ordered a field monitor for my ca...,"July 27, 2020"
17047,Martyn,/users/4f1ec7b20000640001129098,GB,22 reviews,2019-01-08T15:15:54.000Z,Rated 5 out of 5 stars,Excellent.,My experiences have always been excellent and ...,"January 08, 2019"

In [9]:
data['Review Text'][0]

"I registered on the website, tried to order a laptop, entered all the details, but instead of charging me and sending the product, they froze my account, demanding various verification documents. I sent them over. They said they would review them within 24 hours. In reality, it's been a week, and no one can help or give any (truthful) estimate of when it will be resolved; they just tell me to 'wait.' I've never seen such a horrible marketplace in my life. I hope those who came up with this can't buy food in a store, receiving a 'document review request' that takes forever to process."

In [10]:
data.describe()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
count,21214,21163,21054,21055,21055,21055,21055,21055,20947
unique,18531,21156,148,177,21054,5,19277,20407,3640
top,customer,"January 21, 2012",US,1 review,2022-10-05T12:13:39.000Z,Rated 1 out of 5 stars,Excellent,Review text not found,"January 11, 2021"
freq,72,3,9286,5761,2,13123,52,630,32

In [11]:
# -------------
# Column Names
# -------------
data.columns

Index(['Reviewer Name', 'Profile Link', 'Country', 'Review Count',
       'Review Date', 'Rating', 'Review Title', 'Review Text',
       'Date of Experience'],
      dtype='str')

In [12]:
# -------------
# Column Types
# -------------
data.dtypes

Reviewer Name         str
Profile Link          str
Country               str
Review Count          str
Review Date           str
Rating                str
Review Title          str
Review Text           str
Date of Experience    str
dtype: object

In [13]:
data.duplicated().sum()

np.int64(2)

In [14]:
# -----------------------------
# Check for Missing Values
# -----------------------------
data.isna().sum()

Reviewer Name           0
Profile Link           51
Country               160
Review Count          159
Review Date           159
Rating                159
Review Title          159
Review Text           159
Date of Experience    267
dtype: int64

In [15]:
# --------------------------------------------
# Check Missing Values Percentage in Columns
# --------------------------------------------
data.isna().mean().sort_values(ascending=False)

Date of Experience    0.012586
Country               0.007542
Review Title          0.007495
Review Date           0.007495
Review Count          0.007495
Review Text           0.007495
Rating                0.007495
Profile Link          0.002404
Reviewer Name         0.000000
dtype: float64

In [16]:
data = data.drop(columns=[
    'Reviewer Name',
    'Profile Link',
    'Review Count',
    'Review Date',
    'Date of Experience'
])

In [17]:
data = data.dropna(subset=['Review Text', 'Rating'])
data['Review Title'] = data['Review Title'].fillna('')
data['Country'] = data['Country'].fillna('Unknown')

In [18]:
data['Rating'] = data['Rating'].str.extract(r'(\d)').astype(float)
data = data.dropna(subset=['Rating'])
data['Rating'] = data['Rating'].astype(int)

In [19]:
data['Sentiment'] = data['Rating'].apply(lambda x: 1 if x >= 4 else 0 if x <= 2 else None)
data = data.dropna(subset=['Sentiment'])
data['Sentiment'] = data['Sentiment'].astype(int)

In [20]:
data['Full Review'] = data['Review Title'] + " " + data['Review Text']

In [22]:
data.to_csv("../data/processed/clean_reviews.csv", index=False)